# Generated by Django 2.2 on 2020-01-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('opportunity', models.CharField(choices=[('employee', 'Employee'), ('freelancer', 'Ereelancer'), ('internships', 'Internships')], default='employee', max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('remote', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('salary_min', models.IntegerField(blank=True, default=0, null=True)),
                ('salary_max', models.IntegerField(blank=True, default=0, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
