# Generated by Django 2.2 on 2020-01-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torre1_app', '0002_auto_20200124_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='code',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
