# Generated by Django 2.2 on 2020-01-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torre1_app', '0003_opportunity_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity',
            field=models.CharField(choices=[('employee', 'Employee'), ('freelancer', 'Freelancer'), ('internships', 'Internships')], default='employee', max_length=120),
        ),
    ]
