# Generated by Django 2.2 on 2020-01-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torre1_app', '0004_auto_20200124_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='salary_min',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='salary',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
