# Generated by Django 2.2 on 2020-01-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torre1_app', '0006_auto_20200124_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Freelancer', 'Freelancer'), ('Internships', 'Internships')], default='Employee', max_length=120),
        ),
    ]
